groundhopper:
  build: .
  command: go build -o main .
  environment:
    - GOPATH:"/home/app/groundhopper/server"
    - GOBIN:"/home/app/groundhopper/server/bin"
  entrypoint: /home/app/groundhopper/server/src/main
  volumes:
    - ./server:/home/app/groundhopper/server
  ports:
    - "9000:9000"
